site_name: ETL - Projeto Casa de Eventos Thai
repo_url: https://github.com/rbalbinotti/thai_portfolio
repo_name: rbalbinotti/ETL - Projeto Casa de Eventos Thai
edit_uri: tree/main/docs

theme:
    name: material
    language: pt-BR
    logo: assets/logo.jpeg
    favicon: /docs/assets/logo.jpeg

markdown_extensions:
    - attr_list

extra_css:
    - stylesheets/extra.css